//add pharmaproduct
export const ADD_PRODUCT_REQUEST='ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_SUCCESS='ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILURE='ADD_PRODUCT_FAILURE';

//delete pharmaproduct
export const DELETE_PRODUCT_REQUEST='DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS='DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILURE='DELETE_PRODUCT_FAILURE';

//UPDATE pharmaproduct
export const UPDATE_PRODUCT_REQUEST='UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS='UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILURE='UPDATE_PRODUCT_FAILURE';

//getuserlist pharmaproduct
export const GET_USERLIST_REQUEST='GET_USERLIST_REQUEST';
export const GET_USERLIST_SUCCESS='GET_USERLIST_SUCCESS';
export const GET_USERLIST_FAILURE='GET_USERLIST_FAILURE';

//UPDATE pharmaproduct
export const DELETE_USER_REQUEST='DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS='DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE='DELETE_USER_FAILURE';

//getadmistphrmarequet
export const GET_ADMINLIST_REQUEST='GET_ADMINLIST_REQUEST';
export const GET_ADMINLIST_SUCCESS='GET_ADMINLIST_SUCCESS';
export const GET_ADMINLIST_FAILURE='GET_ADMINLIST_FAILURE';


//addadminrerequest
export const ADD_ADMIN_REQUEST='ADD_ADMIN_REQUEST';
export const ADD_ADMIN_SUCCESS='ADD_ADMIN_SUCCESS';
export const ADD_ADMIN_FAILURE='ADD_ADMIN_FAILURE';


//deleteadmin
export const DELETE_ADMIN_REQUEST='DELETE_ADMIN_REQUEST';
export const DELETE_ADMIN_SUCCESS='DELETE_ADMIN_SUCCESS';
export const DELETE_ADMIN_FAILURE='DELETE_ADMIN_FAILURE';

//getcategoriesrequest
export const GET_CATEGORIES_REQUEST='GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS='GET_CATEGORIES_SUCCESS';


//getorderrequest
export const GET_ORDERS_REQUEST='GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCCESS='GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILURE='GET_ORDERS_FAILURE';


//updateorder
export const UPDATE_ORDER_REQUEST='UPDATE_ORDER_REQUEST';
export const UPDATE_ORDER_SUCCESS='UPDATE_ORDER_SUCCESS';
export const UPDATE_ORDER_FAILURE='UPDATE_ORDER_FAILURE';


export const GET_PRODUCTS_REQUEST="GET_PRODUCTS_REQUEST"
export const  GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_FAILURE="GET_PRODUCTS_FAILURE"


export const GET_CARTS_SUCCESS='GET_CARTS_SUCCESS';