export const ADDTOCART = "ADDTOCART";
export const REMOVEFROMCART = "REMOVEFROMCART";
export const CARTPRICE = "CARTPRICE";

export const POST_CART_REQUEST= 'POST_CART_REQUEST';
export const POST_CART_SUCCESS= 'POST_CART_SUCCESS';
export const POST_CART_FAILURE= 'POST_CART_FAILURE';

export const GET_CART_REQUEST= 'GET_CART_REQUEST';
export const GET_CART_SUCCESS= 'GET_CART_SUCCESS';
export const GET_CART_FAILURE= 'GET_CART_FAILURE';

// export const REMOVE_CART_REQUEST= 'REMOVE_CART_REQUEST';
// export const REMOVE_CART_SUCCESS= 'REMOVE_CART_SUCCESS';
// export const REMOVE_CART_FAILURE= 'REMOVE_CART_FAILURE';

// export const EMPTY_CART_REQUEST= 'EMPTY_CART_REQUEST';
// export const EMPTY_CART_SUCCESS= 'EMPTY_CART_SUCCESS';
// export const EMPTY_CART_FAILURE= 'EMPTY_CART_FAILURE';


export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const CLEAR_CART = "CLEAR_CART";