export const ADDTOCART = "ADDTOCART";
export const REMOVEFROMCART = "REMOVEFROMCART";
export const CARTPRICE = "CARTPRICE";

export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const CLEAR_CART = "CLEAR_CART";