export const  GET_SINGLEPRODUCT_LOADING = "GET_SINGLEPRODUCT_LOADING";
export const  GET_SINGLEPRODUCT_SUCCESS = "GET_SINGLEPRODUCT_SUCCESS";
export const  GET_SINGLEPRODUCT_ERROR = "GET_SINGLEPRODUCT_ERROR";
